aqk = input()
a,q,k = aqk.split(" ")
a = int(a)
q = int(q)
k = int(k)
A = list()
l1 = input()
A = l1.split(" ")
A = list(map(int , A))
for i in range(q):
    l,r = input().split(" ")
    l = int(l)
    r = int(r)
    A[l:r+1] = sorted(A[l:r+1])
    print(A)
print(A[k])
